### ISSUE TITLE
Change grid charge sensor to rwsensor

### ISSUE THREAD

**Issue by jacekowski** [kellerza/sunsynk#100]
Existing sensor definitions can be found [here](https://github.com/kellerza/sunsynk/blob/main/sunsynk/definitions.py)

### You Inverter

5kW sunsynk

### Describe the issue/bug and what you expect

I would like to see a change to register 230 (Grid charge current) to be writeable ( https://github.com/kellerza/sunsynk/commit/ee156abe0dc3dfd3798eece9113b345584915b79 - this commit should achieve that) 

I'm on economy 7 tariff so normally have 7hrs to charge my battery so i keep charge current low to help with efficiency and battery life.  I'm also adjusting target SoC based on weather forecast, however, for example today, just 30 minutes before end of cheap period forecast changed to be significantly worse, if that happens i would like to adjust current to allow as much charging as possible and then reset it back to low current for next day.

**Comment by kellerza** [comment]
The library has not been released (version needs to be bumped) and dockerfile updated for the addons

**Comment by cc120689** [comment]
ok, we will wait patiently, thank you!

**Comment by kellerza** [comment]
I updated the library, but did NOT bump the addon version (this is combined with some other changes I have not finished testing, - but it is not related to the dev addon) 

So auto-update will not work, if you delete the dev addon and reinstall the new version should be built in.

**Comment by cc120689** [comment]
ok I'll try it and comment, thanks!

**Comment by kellerza** [comment]
Great stuff!!
