### ISSUE TITLE
batt charge and discharge limits

### ISSUE THREAD

**Issue by cc120689** [kellerza/sunsynk#107]
hello Kellerza, I'm the heavy from Spain again ;)
would it be possible to implement the battery charge and discharge limit  as writable sensors?  the idea is the following, here in Spain the surpluses in the morning are paid at a reasonable price, however in the afternoon when the batteries are full they are paid in thousandths of a euro... it would be nice to be able to lower the charging amperage to 1 ampere in the morning so that surpluses are injected and in the afternoon charge the battery, which is when they almost charge you for injecting into the network.
I am doubting if it would be sensors 314 and 315 or 320 and 321, I have asked colleagues from the telegram group who have it implemented directly with node red to confirm which one they use with Turbo Energy.
thanks again and keep up your fantastic work please
Edit: Sorry, I've already seen it, they are sensors 210 and 211, max A charge and max A discharge

**Comment by kellerza** [comment]
Please paste the full stack trace, on its own that means relatively little…

**Comment by cc120689** [comment]
this is:
023-03-14 19:59:29,167 DEBUG   avg unit:°C, id:radiator_temperature
2023-03-14 19:59:29,167 DEBUG   last unit:, id:grid_connected_status
2023-03-14 19:59:29,168 DEBUG   step unit:, id:control_mode
Traceback (most recent call last):
  File "/usr/src/app/./run.py", line 472, in <module>
    startup()
  File "/usr/src/app/./run.py", line 261, in startup
    setup_sensors()
  File "/usr/src/app/./run.py", line 307, in setup_sensors
    for dep in sen.dependencies():
TypeError: 'list' object is not callable
[cmd] ./run.py exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
and this is definitions :
BATTERY_FLOAT_VOLTAGE = NumberRWSensor(
    203, "Battery Float voltage", VOLT, 0.01, min=MIN_VOLTAGE, max=MAX_VOLTAGE
)
MAX_CHARGE_CURRENT = NumberRWSensor(
    210,
    "Max Charge Current", 
    "AMPS",
    min=0,
    max=185,
    )
MAX_DISCHARGE_CURRENT = NumberRWSensor(
    210,
    "Max Discharge Current",
    "AMPS",
    min=0,
    max=185,
    )
BATTERY_SHUTDOWN_CAPACITY = NumberRWSensor(217, "Battery Shutdown Capacity", "%")

**Comment by cc120689** [comment]
I have also tried this with the same result:

#############
# Inverter settings
#############
_SENSORS.append(
    NumberRWSensor(230, "Grid Charge Battery current", AMPS, min=0, max=185)
)
_SENSORS.append(
    NumberRWSensor(210, "Max Charge Current", AMPS, min=0, max=185)
)
_SENSORS.append(
    NumberRWSensor(211, "Max Discharge Current", AMPS, min=0, max=185)
)

**Comment by cc120689** [comment]
Yes i am using dev, i will try as soon as posible and post results, thanks!!

**Comment by cc120689** [comment]
This is result with this def:

#############
# Inverter settings
#############
_SENSORS.append(
    NumberRWSensor(230, "Grid Charge Battery current", AMPS, min=0, max=185)
)
_SENSORS.append(
    NumberRWSensor(210, "Max Charge Current", AMPS, min=0, max=185)
)
_SENSORS.append(
    NumberRWSensor(211, "Max Discharge Current", AMPS, min=0, max=185)
)

Log:

2023-03-18 10:16:48,740 DEBUG   avg unit:V, id:battery_charging_voltage
2023-03-18 10:16:48,740 DEBUG   step unit:%, id:bat1_soc
2023-03-18 10:16:48,740 DEBUG   step unit:, id:bat1_cycle
2023-03-18 10:16:48,740 WARNING Sensor prog1_time only allowed once
Traceback (most recent call last):
  File "/usr/src/app/./run.py", line 472, in <module>
    startup()
  File "/usr/src/app/./run.py", line 261, in startup
    setup_sensors()
  File "/usr/src/app/./run.py", line 325, in setup_sensors
    sen.on_change = lambda sen=sen, deps=deps: enqueue_hass_discovery_info_update(
  File "/usr/local/lib/python3.9/site-packages/attr/_make.py", line 1065, in __setattr__
    _obj_setattr(self, name, nval)
AttributeError: 'NumberRWSensor' object has no attribute 'on_change'
[cmd] ./run.py exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by kellerza** [comment]
Can you try the new (multi) addon? These sensors should now be included

**Comment by cc120689** [comment]
Do I install it as is without modifying anything?

**Comment by kellerza** [comment]
With the new addon you can create your own custom sensors

The new docs on this - not live yet - can be found here: https://github.com/kellerza/sunsynk/blob/main/www/docs/reference/mysensors.md

**Comment by cc120689** [comment]
You are a machine, it goes like a shot.  In "port:" I have put "" as in the old config and for the rest to the first.  thank you so much!  I'm going to look at the new sensors, thanks again!

**Comment by kellerza** [comment]
In port you now need to put your full string: `serial://dev/myusb` or `tcp://ip:port`

you can use the debug_device to help you with the myusb part

**Comment by cc120689** [comment]
I am adding a custom sensor to test: 293 "grid peak saving power" and in the log it seems to work but the sensor does not appear later.
Log:
2023-03-19 19:33:41,185 INFO    Importing /share/hass-addon-sunsynk/mysensors.py...
2023-03-19 19:33:41,185 INFO      custom sensors: grid_peak_shaving_power
2023-03-19 19:33:41,187 INFO    Added hidden sensors as other sensors depend on it:

**Comment by kellerza** [comment]
Currently you also have to add it to your config in the addon...

```
SENSORS:
 - grid_peak_shaving_power
```

Could maybe look at adding all these automatically

**Comment by cc120689** [comment]
What a fool!!  she hadn't noticed it.  thanks now yes!!

**Comment by kellerza** [comment]
New docs :wink: https://kellerza.github.io/sunsynk/reference/mysensors

**Comment by kellerza** [comment]
btw, if you finally have it working, please give feedback, or even better, create a PR on `definitions.py` so that other people can benefit from your idea

It would also be great if you can describe your use-case/automation that you use. You can describe that here: https://kellerza.github.io/sunsynk/examples/a-mode

There is a "edit this page on github" link

**Comment by cc120689** [comment]
I don't know what change to propose in definitions.py, you have already done everything, what I have done is put the example of use of the automation in the link that you have given me, I don't know if you were referring to that, it is the first time I write something on github, thanks again for your work!

**Comment by kellerza** [comment]
Hi @cc120689 

Thank you! I can see you made a change to your fork in patch-1 - https://github.com/cc120689/sunsynk/blob/patch-1/www/docs/examples/a-mode.md

What you need to do now is create a [PR - Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) There should be a yellow banner on that link that you can use to start this, or simply a **Pull request** button. With the PR I can then add it to the main repository

**Comment by cc120689** [comment]
I think I did it, thank you!

**Comment by cc120689** [comment]
Working perfectly
