### ISSUE TITLE
Outdated add-on

### ISSUE THREAD

**Issue by w1tw0lf** [kellerza/sunsynk#119]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue

Addon seems to be outdate, have version: 2022.11.29-0.2.5 

**Expected behavior**

Looking at https://github.com/kellerza/sunsynk/releases, latest seems to be version 0.3.1
Checking for updates doesn't resolve it.

### Your environment

- Home Assistant version: 2023.3.6
- Addon version: 2022.11.29-0.2.5

**Comment by kellerza** [comment]
Please try the (multi) addon

It has breaking config changes, so there is no smooth upgrade path
