### ISSUE TITLE
grid_ct_power_export sensor 

### ISSUE THREAD

**Issue by amctear** [kellerza/sunsynk#127]
My Sunsynk addon x 2 have been working wonderfully since installed and set, thanks to Johann.  An interesting Blueprint PV solar excess optimizer - auto control, has recently been released which requres some template skills to generate a new sensor **Export power to the grid in watts.**  
Sadly, I don't have the skills to strip out the **grid power out** portion from the **grid power sensor**.  Hoping someone can help please
![image](https://user-images.githubusercontent.com/7934654/233111153-6da6f6f4-a56f-44a9-8627-f76d8bb9b5f6.png)

Blueprint
[https://community.home-assistant.io/t/pv-solar-excess-optimizer-auto-control-appliances-wallbox-dish-washer-heatpump-based-on-excess-solar-power/552677](url)

**Comment by kellerza** [comment]
```yaml
SENSORS:
 - grid_ct_power
```

The template could be something like this?
 
```
{{ -states("sensor.ss_grid_ct_power") if int(states("sensor.ss_grid_ct_power"))<0 else 0 }}
```

Let us know how it goes, I'll also have a look at the referenced project!

**Comment by amctear** [comment]
Thanks, Will give it a try
