### ISSUE TITLE
ESP Integration | The Entity Is Unavailable | sensor.eskomsepushallowance

### ISSUE THREAD

**Issue by vexersa** [kellerza/sunsynk#128]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

When following the guide to add the ESP lovelace card, the following error is presented:

![image](https://user-images.githubusercontent.com/7994227/233352945-babbae0a-0bb1-4a9e-834e-7e57c8f22b2e.png)
![image](https://user-images.githubusercontent.com/7994227/233352968-4aaee715-5423-43b4-a228-0eb14c2cc318.png)

Seems to be related to this: 
https://www.home-assistant.io/faq/unique_id

**Expected behavior**
The card to work correctly.

### Your environment

Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest
Sunsynk Inverter Add-on (multi)
Current version: 2023.03.19b-0.3.1

### Logs

```log
paste logs in 3x backticks...
```

**Comment by kellerza** [comment]
Updated the docs to make it a bit clearer, start here: https://kellerza.github.io/sunsynk/examples/overview#config-packages

Once you have the package loaded you should have new eskom entities - you can see these in Dev tools > States

<img width="264" alt="image" src="https://user-images.githubusercontent.com/6756881/233362893-ebcf59a0-a118-4c87-b132-902877ffe603.png">

If all of this is new, read the Home Assistant docs & join the HA Community forum

**Comment by vexersa** [comment]
Great, that fixed it. Thanks for the knowledge 🙏
