### ISSUE TITLE
Failed to install add-on - Any ideas - MULTI Version

### ISSUE THREAD

**Issue by cakuhn** [kellerza/sunsynk#130]
Failed to install add-on
The command '/bin/ash -o pipefail -c pip3 install --no-cache-dir --disable-pip-version-check paho-mqtt~=1.5.0 pyyaml~=5.4.1 mqtt-entity sunsynk[pymodbus,umodbus]==0.3.1' returned a non-zero code: 1

Multi Version of Sunsync Add On

Any ideas why this would happen?

**Comment by kellerza** [comment]
Search the HASS community forum, there might be additional pointers

**Comment by cakuhn** [comment]
Thank you
