### ISSUE TITLE
Sunsynk Power Flow Card | 404 Error for repo link

### ISSUE THREAD

**Issue by vexersa** [kellerza/sunsynk#158]
### Issue related to

Sunsynk Power Flow Card

### Describe the issue/bug

The repo link on this page does not work: 
https://kellerza.github.io/sunsynk/examples/lovelace

**Expected behavior**
Clicking this link should allow for the repo to be installed in HA: https://my.home-assistant.io/redirect/hacs_repository/?repository=sunsynk-power-flow-card&category=plugin&owner=slipx06

![image](https://github.com/kellerza/sunsynk/assets/7994227/9f731e94-d9d5-46c6-8a86-b66bab74e9b4)

**Comment by kellerza** [comment]
It works for me :wink:

You will have to be a lot more specific on what happens when you click it, what browser you are using, etc, else theres no way of helping you
