### ISSUE TITLE
How to enable essential load 1 & 2 on HA Add-On?

### ISSUE THREAD

**Issue by k2dp2k** [kellerza/sunsynk#176]
Hey hoo,

how can i enable the two sensors on HA-Add-On?
My inverter is running off-grid, without pv connected, it is fed by an mi on the gen port, so the standard essential load delivers wrong values...

My best :-)

**Comment by kellerza** [comment]
Hi, maybe load_1_power?

https://github.com/kellerza/sunsynk/blob/main/src/sunsynk/definitions.py#L63

**Comment by k2dp2k** [comment]
Nope, thats not working... non of the load 1,2 ore essential 1,2 are coming up when i define them in den add-on...

**Comment by kellerza** [comment]
Load_l1_power?

**Comment by k2dp2k** [comment]
Thats working ;-) Thank you!
Btw... all the essential loads are displaying the same value, essential 2 is displaying an positive value instead of a negative one...

**Comment by kellerza** [comment]
Great!

You probably want to look at `aux_power` as well. Since you have a fairly unique setup it might take some experimenting to see which sensors works for you (the sensors simply translate to registers on the inverter)
