### ISSUE TITLE
Max Power output Sunsynk 5kw

### ISSUE THREAD

**Issue by e1ace** [kellerza/sunsynk#181]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

Prog 1 through 6 is limited to between 0 and 5000w.

**Expected behavior**
The data sheet for the 5kw Sunsynk says a max of 5500w output. If I adjust the settings on the inverter itself I can set between 0 and 5500w, but on the Add-On it is limited.

### Your environment

- Home Assistant version: 2023.8.x
- Addon:
  - Name: sunsynk-multi
  - Version: 2023-09-04
- Inverter:
  - Make: Sunsynk
  - Model: 5kW
  - Firmware: \_\_
- Adaptor details:
  - RS485

**Comment by kellerza** [comment]
What do you see in Settings->Devices?
![image](https://github.com/kellerza/sunsynk/assets/6756881/80094394-6576-49d3-b02a-d4b7017f9585)

The max is read from the inverter (`RATED_POWER`). The only way to force it would be a custom sensor - see the docs.

You need to redefine these sensors in `mysensors.py`, set `RATED_POWER` to 5500 

```python
    NumberRWSensor(256, "Prog1 power", WATT, max=5500),
    NumberRWSensor(257, "Prog2 power", WATT, max=RATED_POWER),
    NumberRWSensor(258, "Prog3 power", WATT, max=RATED_POWER),
    NumberRWSensor(259, "Prog4 power", WATT, max=RATED_POWER),
    NumberRWSensor(260, "Prog5 power", WATT, max=RATED_POWER),
    NumberRWSensor(261, "Prog6 power", WATT, max=RATED_POWER),
```

**Comment by e1ace** [comment]
![Screenshot_2023-09-09-10-19-48-48_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/kellerza/sunsynk/assets/20770537/a3c8525b-acf5-4f38-ad04-c8968f407806)

Thanks. The redefined sensors works.
