### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by jacekowski** [kellerza/sunsynk#189]
Currently, only tcp and serial-tcp are supported with both umodbus and pymodbus.

It should be relatively easy to implement udp and serial-udp with pymodbus (umodbus is going to be more difficult due to underlying connio library not supporting it).

After testing with few adapters i own it seems like udp causes less issues (especially over wifi).

**Comment by kellerza** [comment]
Hi @jacekowski - if you tested it, you should be mostly there to submit a PR as well 😉

**Comment by kellerza** [comment]
Added in #191 - thanks @jacekowski !
