### ISSUE TITLE
DEBUG_DEVICE not found

### ISSUE THREAD

**Issue by Elsorus** [kellerza/sunsynk#214]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

Error message trying to start add-on and saving config:
Device /dev/ttyAMA0 does not exist in Sunsynk/Deye Inverter Add-on (multi) (4bb530c7_hass-addon-sunsynk-multi).

Tried changing the setting in YAML from /dev/ttyAMA0 to some of the items listed under dev like /dev/stdout but cannot save the config complaining the DEBUG_DEVICE was not found.

**Expected behavior**
Add-on not starting after Home Assistant OS upgrade to 11.2

### Your environment

- Home Assistant version: 2023.11. 3
- Addon:
  - Name: sunsynk-multi
  - Version: 0.6.4
- Inverter:
  - Make: Sunsynk

### You configuration

```
DRIVER: umodbus
INVERTERS:
  - SERIAL_NR: "22073XXXXX"
    HA_PREFIX: SS
    MODBUS_ID: 1
    PORT: tcp://10.0.0.54:502
SENSOR_DEFINITIONS: single-phase
SENSORS:
  - total_pv_energy
  - total_battery_charge
  - total_battery_discharge
  - total_grid_export
  - total_grid_import
  - battery_soc
  - essential_power
  - interter_power
  - grid_power
  - non_essential_power
  - battery_current
  - battery_voltage
  - Day Active Energy
  - inverter_power
  - battery_power
  - Grid Connected Status
  - Grid voltage
  - Load power
  - PV1 power
  - PV2 power
  - settings
  - load_limit
  - grid_connected
SENSORS_FIRST_INVERTER:
  - single-phase
MANUFACTURER: Sunsynk
READ_ALLOW_GAP: 5
READ_SENSORS_BATCH_SIZE: 60
SCHEDULES:
  - KEY: W
    READ_EVERY: 5
    REPORT_EVERY: 60
    CHANGE_ANY: false
    CHANGE_BY: 80
    CHANGE_PERCENT: 0
NUMBER_ENTITY_MODE: auto
MQTT_HOST: homeassistant.d
MQTT_PORT: 1883
MQTT_USERNAME: mqttadmin
MQTT_PASSWORD: mqttpwd
DEBUG: 0
DEBUG_DEVICE: /dev/ttyAMA0

```

**Comment by kellerza** [comment]
Do you see any other options in visual mode?

Its not being used in your config, so simply select anything that is avaliable

**Comment by Elsorus** [comment]
Unfortunately, there is nothing displayed. No radio button(s) as is the case in OS version 11.1
![image](https://github.com/kellerza/sunsynk/assets/5388312/d65777db-2a6d-43f0-a9ae-b7e232181b9a)

**Comment by kellerza** [comment]
Did this work before an upgrade?

**Comment by Elsorus** [comment]
This all started after the upgrade from HA OS 11.1 to 11.2.
I have some automations that depend on the inverter formation so I rolled back to 11.1 and all is working again

**Comment by arzaman** [comment]
> Did this work before an upgrade?

my first installation so I have no previous experience

home assistant core 2023.11.3
did everthing from scratch

PS did also several restart/browser cache cleaning/different browser used
thanks
Davide

**Comment by duanemck** [comment]
Just had the same issue after upgrading to 11.2
Luckily I still had another device listed under DEBUG_DEVICE that I could pick which solved the issue.

![image](https://github.com/kellerza/sunsynk/assets/429394/1b1bc18d-afb1-4895-983f-4d8c77553b72)

**Comment by kellerza** [comment]
It seems /dev/AMA0 was removed in 11.2.

The result is that if you have no actual USB device on your host, which is normal for a install using mbusd on a remote device, you might have an issue

`DEBUG_DEVICE` should now be optional in 0.6.5

**Comment by arzaman** [comment]
I try to update/reinstall 0.6.5 but now got an error during installation ..

Can't install ghcr.io/kellerza/hass-addon-sunsynk-multi/aarch64:0.6.5: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.6.5&fromImage=ghcr.io%2Fkellerza%2Fhass-addon-sunsynk-multi%2Faarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

**Comment by kellerza** [comment]
It should now be avaialble

**Comment by arzaman** [comment]
It works fine now for me !
great and prompt support, thank you
Davide

**Comment by arzaman** [comment]
@kellerza since you are so kind little bit of assistance more (not related to above issue)

all works flowlsessly ...really cool integration with no extra HW !

the only little issue that PV2 voltage/current counters are missing ..just POWER is reporte, PV1 all OK !

![image](https://github.com/kellerza/sunsynk/assets/6697518/c14cc30d-e8a4-4935-8ae7-8b60541cb5e1)

my inverter DEYE 5KW hybrid inverter SUN-3.6/5/6K-SG03LP1-EU 
let me know if something I can fix by myself

thanks again
Davide

**Comment by kellerza** [comment]
It might be part of the definitions today (these you add simply by adding the name to config)

if not in the definitions, you can add new definitions with mysensors - search mysensors in the docs. Its fairly easy to add additional ones

**Comment by Elsorus** [comment]
Closing as this was related to the HA OS upgrade and DEBUG_DEVICE was made optional in 0.6.5

**Comment by Elsorus** [comment]
Closing as this was related to the HA OS upgrade and DEBUG_DEVICE was made optional in 0.6.5
