### ISSUE TITLE
Upgrading from 0.6.4 to 0.6.5 fails

### ISSUE THREAD

**Issue by jrkk0925** [kellerza/sunsynk#215]
### Issue related to

Sunsynk Home Assistant Add-On

### Describe the issue/bug

Updating to v0.6.5 returns an error
 
Can't install ghcr.io/kellerza/hass-addon-sunsynk-multi/aarch64:0.6.5: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.6.5&fromImage=ghcr.io%2Fkellerza%2Fhass-addon-sunsynk-multi%2Faarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

### Your environment

Core 2023.12.1
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

### Logs

```Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 11:52:20 AM (1 occurrences)
Last logged: 11:52:20 AM

Failed to to call /store/addons/4bb530c7_hass-addon-sunsynk-multi/update - Can't install ghcr.io/kellerza/hass-addon-sunsynk-multi/aarch64:0.6.5: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.6.5&fromImage=ghcr.io%2Fkellerza%2Fhass-addon-sunsynk-multi%2Faarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

**Comment by theowinter** [comment]
Same for me:

`Can't install ghcr.io/kellerza/hass-addon-sunsynk-multi/amd64:0.6.5: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.6.5&fromImage=ghcr.io%2Fkellerza%2Fhass-addon-sunsynk-multi%2Famd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

**Comment by rogeralexanderdean** [comment]
Same issue here

![Screenshot_2023-12-08-21-54-05-363_io homeassistant companion android](https://github.com/kellerza/sunsynk/assets/95184748/7a06728e-cb3d-431b-9f64-50ea07031175)

**Comment by kellerza** [comment]
It should now be available

**Comment by theowinter** [comment]
Da'sy! Sukses! Dankie Johann.
