### ISSUE TITLE
Charge Amps 

### ISSUE THREAD

**Issue by Leecavturbo** [kellerza/sunsynk#222]
My inverter 5kw SS has Charge Amps and Grid Amps in battery settings. The sensor definition grid_charge_battery_current is the Grid Amps but I don’t see definition for Charge Amps. It is found ?

```

**Comment by kellerza** [comment]
Hi, please have a look at the modbus protocol document. Feel free to add custom sensors/mysensors to experiment with new registers

**Comment by Leecavturbo** [comment]
Thanks Johan. I found all bar 1 . Max sell power

**Comment by kellerza** [comment]
Did you do a custom sensor for max sell power? Do you mind sharing it?

**Comment by Leecavturbo** [comment]
Hi Johan, no it’s the one I can’t find ! I’ve tried max_sell ,
max_sell_power , sell_power and other possible combinations but no joy.

**Comment by rixxxx** [comment]
This is not implemented for 1PH inverters. 1PH documentation I have doesn't list anything similar.

**Comment by Leecavturbo** [comment]
I have that working now !!! 1ph

**Comment by rixxxx** [comment]
Please share what you did to get it to work?

**Comment by Leecavturbo** [comment]
Here is what I have .
And result in Mqtt

**Comment by Leecavturbo** [comment]
I just can’t find and need Max Sell now and I’ll have every setting I need

**Comment by rixxxx** [comment]
Yeah, I'm talking about documentation lacking info about Max Sell.

**Comment by Leecavturbo** [comment]
Still stuck on that . I tried several obvious combinations of wording and
still no joy

**Comment by rixxxx** [comment]
As I said, there is no code to handle that and at least the documentation I have is lacking the regisgers to implement that.

**Comment by jacekowski** [comment]
`SENSORS += NumberRWSensor(53, "Max Solar Power", WATT, 1, min=0, max=10000)
`

**Comment by kellerza** [comment]
Thx @jacekowski - these are now in the 1ph definition files
