### ISSUE TITLE
Full PV Power Generation

### ISSUE THREAD

**Issue by tuanha2000vn** [kellerza/sunsynk#25]
It's possible to get the full PV Power Generation sensor value?

If solar sell disabled, the PV only generate enough power for load + batt charge.

This sensor is useful for people who can't sell power but would like to know if there is an extra power to turn on no crucial devices like pool pump, water heater...

Thank you.

**Comment by kellerza** [comment]
I’m not sure this is possible, since it will depend on the panels&mppt tracker and not something the inverter can measure without any load

There is a solar forecast sensor in homeassistant that you could try

**Comment by tuanha2000vn** [comment]
Currently I'm using a light sensor (BH1750) to calculate the estimate PV power production but I hope you can find that sensor value hiding somewhere inside the inverter.

Hope you can make it someday. This is a really great add-on. Thank you.

**Comment by poldim** [comment]
> Currently I'm using a light sensor (BH1750) to calculate the estimate PV power production but I hope you can find that sensor value hiding somewhere inside the inverter.
> 
> Hope you can make it someday. This is a really great add-on. Thank you.

I don't think a light sensor is equivalent to solar irradiance as brightness is different than the "power" from the sun.
