### ISSUE TITLE
Custom Sensors​ seems not to work

### ISSUE THREAD

**Issue by basti122303** [kellerza/sunsynk#252]
### You Inverter:

Deye 10K

I use the generator port for mirco inverter Input and  have create a custom sensor.
```
[core-ssh share]$ cat /share/hass-addon-sunsynk/mysensors.py
from sunsynk import AMPS, CELSIUS, KWH, VOLT, WATT
from sunsynk.rwsensors import NumberRWSensor, SelectRWSensor, TimeRWSensor
from sunsynk.sensors import (
    MathSensor,
    Sensor,
    SensorDefinitions,
    TempSensor,
)

SENSORS = SensorDefinitions()

SENSORS += Sensor(667, "mi_input", WATT, -1)
[core-ssh share]$ 
```
The sensor is load:

```
12:53:09 INFO    Importing /share/hass-addon-sunsynk/mysensors.py...
12:53:09 INFO      custom sensors: mi_input
```
But there are no values and it seems not to be queried:
```
12:53:10 INFO    Report every (inverter 1)
+-----+--------------------------------------------------------------------------------+
|  s  |                                    Sensors                                     |
+-----+--------------------------------------------------------------------------------+
|  5  | inverter_power, pv2_power, grid_power, pv1_power, grid_ct_power, battery_power |
| 300 | prog1_charge, prog1_power, total_grid_export, total_pv_energy, prog5_capacity, |
|     |       overall_state, prog6_time, battery_current, day_battery_discharge,       |
|     |     day_load_energy, use_timer, prog4_power, prog6_charge, grid_frequency,     |
|     |    total_grid_import, load_limit, prog2_capacity, prog3_power, prog5_time,     |
|     |       day_grid_import, prog2_time, battery_soc, pv1_current, prog4_time,       |
|     | prog4_capacity, prog2_charge, prog3_capacity, battery_voltage, day_pv_energy,  |
|     |  total_battery_discharge, prog1_time, prog2_power, prog6_power, prog5_charge,  |
|     |    prog4_charge, grid_voltage, battery_low_capacity, total_battery_charge,     |
|     |  priority_load, pv1_voltage, prog3_time, prog1_capacity, day_battery_charge,   |
|     |   day_grid_export, prog3_charge, prog5_power, grid_connected, prog6_capacity   |
+-----+--------------------------------------------------------------------------------+
```

**Comment by RhysMcW** [comment]
The sensor probably is working it's just that there is no data from the inverter on that register...
When I was still using Nodered I tried retrieving data for the registers in the 600 range but never received any data from the inverter.

what are you expecting to get from that register? - the modbus register docs I have refer to batt5 cycle number for register 667

**Comment by basti122303** [comment]
I get data via mbpoll: 
```
mbpoll -a 1 -b 9600 -0 -P none  192.168.xxx.xxx -m tcp -1 -c 1 -r 667
mbpoll 1.0-0 - FieldTalk(tm) Modbus(R) Master Simulator
...
-- Polling slave 1...
[667]: 	118
```
667 is 'total power of Gen port'
All deye Registers are in the PDF.
[Deye.MODBUS.RTU.V104.1.pdf](https://github.com/kellerza/sunsynk/files/14435135/Deye.MODBUS.RTU.V104.1.pdf)

**Comment by basti122303** [comment]
yes i use this.
I do not understand why the sensor is load but i cant found it in the list of reported sensors. the the post above.

**Comment by RhysMcW** [comment]
> yes i use this. I do not understand why the sensor is load but i cant found it in the list of reported sensors. the the post above.

I think what Johann is asking is if you added either your specific custom sensor or the mysensors option to your "SENSORS" list in the config
![image](https://github.com/kellerza/sunsynk/assets/14996001/9939f0d2-6e6c-4bc4-a5c3-0e2c00d96ad2)
then it would appear in the Sensors list in the log and in HA

**Comment by basti122303** [comment]
Thanks, that helped, I misunderstood.

Who can I change the device class of a custom sensor?

**Comment by kellerza** [comment]
The addon uses this - https://github.com/kellerza/mqtt_entity/blob/main/mqtt_entity/helpers.py#L19

Why do you need to change it?
