### ISSUE TITLE
3 phase Grid Trickle Feed

### ISSUE THREAD

**Issue by khems** [kellerza/sunsynk#260]
Existing sensor definitions can be found [here](https://github.com/kellerza/sunsynk/blob/main/src/sunsynk/definitions.py)

### You Inverter

Sunsynk 3 phase 10kW hybrid

### Describe the issue/bug and what you expect

Hi, do any of you know the address for "Grid Tricke Feed"? I've looked at Deye 3p modbus address list word document but can't find it listed. I also had a look at 206 but that must be a different inverter because it doesn't match up for mine. If I change the value directly on the inverter, it just changes back straight away

Thanks,

**Comment by rixxxx** [comment]
Do you mean "System Zero Export power"? Its already implemented and using register 104.

**Comment by khems** [comment]
What a legend!! Thanks so much!

**Comment by khems** [comment]
It still keeps resetting itself to 20 when I change it though, any ideas?

**Comment by rixxxx** [comment]
Depending on the software installed, it may not support values below 20. If I remember correctly, older releases supported 0, but newer(don't know when it exactly happened) doesn't.

**Comment by khems** [comment]
Thank you so much - that must be the issue! They updated my firmware recently - before it had no problem with being set to 0
