### ISSUE TITLE
Slider scaling

### ISSUE THREAD

**Issue by mathiassmeds** [kellerza/sunsynk#266]
Slider scaling not properly working, max scale seems to be 8000 on the slider, but can receive larger numbers from inverter.

![image](https://github.com/kellerza/sunsynk/assets/115108505/8e3c5ab4-9c9c-4f2c-aaa6-b30745bfb6bc)

**Comment by kellerza** [comment]
What sensor is that?

**Comment by mathiassmeds** [comment]
number.sunsynk_system_mode_power_time1, guess the scale should be settable as this differs on inverter size. I think 10k inv should be max 10000W, so on.

**Comment by kellerza** [comment]
This max is according to the rated_power sensor. Which seems to be 8000?

**Comment by kellerza** [comment]
Please re-open if this is still an issue
