### ISSUE TITLE
Version b381a73 WARNING use_timer: Unknown register value 255 The Problem 

### ISSUE THREAD

**Issue by JanKraslice** [kellerza/sunsynk#268]
Problem recurring every 15 seconds after update
09:59:01 WARNING Cannot publish Use Timer: value is None
09:59:15 WARNING use_timer: Unknown register value 255

Inverter DEYE 3 Phase High Voltage 
Deye 30K 

No problem before update

Is a rollback to previous version or quick fix possible? Please advise
![use_timer](https://github.com/kellerza/sunsynk/assets/150186550/5e44c6c1-a6e1-4e67-8129-6b4ebc22c72b)

**Comment by JanKraslice** [comment]
After switching off and on again with the command 
use_timer OFF
use_timer ON 
The error in the log has stopped showing up, probably will want to treat for future releases
![use_timer on-off](https://github.com/kellerza/sunsynk/assets/150186550/42d68c8e-54ed-4758-a2d9-3d20d796ae48)

**Comment by rixxxx** [comment]
Its most probably due to the bug I fixed with #264 . HA had some now non-existing wrong value cached.

**Comment by kellerza** [comment]
@JanKraslice can you please check if this is still present in the latest dev version?

**Comment by JanKraslice** [comment]
hello latest dev version tested and everything is fine.

Thank you very much, you are the best

**Comment by JanKraslice** [comment]
hello version latest dev s (fix @rixxxx submitted) tested and all is well.
The value is written correctly 1:1
Tested with three phase HV inverter version

Thank you very much, you are the best

**Comment by kellerza** [comment]
Great!
Thx @rixxxx
