### ISSUE TITLE
Possibility of use in sofar 5 ktlm g3?

### ISSUE THREAD

**Issue by Picard2002** [kellerza/sunsynk#275]
I have a Sofar 5ktlm g3 inverter with Solarman WiFi dongle and Solarman ddzy422-d2 WiFi energy meter, with the integration of HACS Solarman, I do not obtain energy data sent to the network or consumption, could this integration be useful to me in my Home assistant?

**Comment by kellerza** [comment]
You can try, but there are other sofar models also not working #265
You could try wiring up the RS485 port
