### ISSUE TITLE
Parameter settings for example ss_prog_power enters multiples of values instead of 1000 enters 10 000 

### ISSUE THREAD

**Issue by JanKraslice** [kellerza/sunsynk#286]
Hello, the problem is in the value of the setting parameters!
Parameter settings for example ss_prog_power
any parameter 1 - 6 value is entered in multiples or kW but HA displays W! Or there is an error in the semicolon value.

If you enter 1000W into the inverter, 10000W is entered, see photo

Please correct
![Deye-PROG power](https://github.com/kellerza/sunsynk/assets/150186550/8da5dfba-6817-483a-9a74-155fbb599ede)
![Deye-PROG power](https://github.com/kellerza/sunsynk/assets/150186550/0cec34d4-de8a-49fe-99a3-0121ad73e0fa)

**Comment by kellerza** [comment]
Hi, what inverter do you have?

You can try to use custom sensors and add a factor parameter

```python
SENSORS += (
    # The max power that can be used from the battery
    NumberRWSensor(256, "Prog1 power", WATT, max=RATED_POWER, factor=10),
    NumberRWSensor(257, "Prog2 power", WATT, max=RATED_POWER, factor=10),
```

**Comment by JanKraslice** [comment]
I'll add
In the previous version it was fine. ( I change the mentioned value in automation)
Only yesterday I updated to version b092637 and shortly afterwards I found that the Prog power parameter is written to the inverter with 10 times the value.

My inverter is SUN-30K-SG01HP3-EU-BM3

I've been using your add-on for several months and until the update to version b092637 everything was fine, including the Prog power value.


Would you have to guide me how to create a custom sensor with parameters ideally a video how to with a tutorial I didn't understand.

Thank you

**Comment by JanKraslice** [comment]
> Ahoj, jaký máš invertor?
> 
> Můžete zkusit použít vlastní senzory a přidat parametr faktoru
> 
> ```python
> SENSORS += (
>     # The max power that can be used from the battery
>     NumberRWSensor(256, "Prog1 power", WATT, max=RATED_POWER, factor=10),
>     NumberRWSensor(257, "Prog2 power", WATT, max=RATED_POWER, factor=10),
> ```

I'll add
In the previous version it was fine. ( I change the mentioned value in automation)
Only yesterday I updated to version b092637 and shortly afterwards I found that the Prog power parameter is written to the inverter with 10 times the value.

My inverter is SUN-30K-SG01HP3-EU-BM3

I've been using your add-on for several months and until the update to version b092637 everything was fine, including the Prog power value.


Would you have to guide me how to create a custom sensor with parameters ideally a video how to with a tutorial I didn't understand.

Thank you

**Comment by JanKraslice** [comment]
I tracked down the release history.

Originally the definition of Phase 3 VN was
SENSORS += (
    NumberRWSensor(154, "Prog1 power", WATT, 10, max=RATED_POWER),
    NumberRWSensor(155, "Prog2 power", WATT, 10, max=RATED_POWER),
    NumberRWSensor(156, "Prog3 power", WATT, 10, max=RATED_POWER),
    NumberRWSensor(157, "Prog4 power", WATT, 10, max=RATED_POWER),
    NumberRWSensor(158, "Prog5 power", WATT, 10, max=RATED_POWER),
    NumberRWSensor(159, "Prog6 power", WATT, 10, max=RATED_POWER),
)

New from version b092637 you have
 NumberRWSensor(154, "Prog1 power", WATT, max=RATED_POWER),
    NumberRWSensor(155, "Prog2 power", WATT, max=RATED_POWER),
    NumberRWSensor(156, "Prog3 power", WATT, max=RATED_POWER),
    NumberRWSensor(157, "Prog4 power", WATT, max=RATED_POWER),
    NumberRWSensor(158, "Prog5 power", WATT, max=RATED_POWER),
    NumberRWSensor(159, "Prog6 power", WATT, max=RATED_POWER),

there's a missing , 10 

**Will you fix it for the next version?**

**Comment by rixxxx** [comment]
#289

**Comment by kellerza** [comment]
@JanKraslice please test with the fix @rixxxx submitted
