### ISSUE TITLE
Sunsynk Docker

### ISSUE THREAD

**Issue by tuanha2000vn** [kellerza/sunsynk#31]
I LOVE this addon. The only downside is it require Home Assistant Supervised installation. On my Synology it mean you have install a virtual machine which is resource consuming.

It's possible to run this via Docker Container?

Thank you.

**Comment by kellerza** [comment]
It should be possible to run this via docker, you just have to creeate your own config test file

If you map a manually crafted "config.json" to the root of the docker container docker container it should work...

```
git clone https://github.com/kellerza/sunsynk.git
cd sunsynk/hass-addon-sunsynk
docker build -t sunsynk
cd ..   # change to the path containing config.json
docker run -v $(pwd)/config.json:/config.json --name sunsynk sunsynk
```

**Comment by tuanha2000vn** [comment]
Thank, wish  you publish it to docker hub someday

**Comment by kellerza** [comment]
It uses the exact same config mechanism!

you are welcome to do some more research on the topic and come with a proposal 😉

**Comment by Ivan-L** [comment]
@tuanha2000vn I also struggled with this as I ran Home Assistant Core on my Synology NAS in a Docker container. I then tried running HASSOS in a virtual machine but as you mentioned, that was a lot slower and more resource intensive. Finally I found this, which has been working very well for me:
https://gist.github.com/maeneak/851e883eca7cddd7114f7eaed201ca9d
I now run a Home Assistant Supervised installation on my NAS using Docker without the overhead of a VM.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/16413523/170882563-8522bd59-fc29-490a-8ec2-f04b5bb90b88.png">

**Comment by jpmeijers** [comment]
> ```
> git clone https://github.com/kellerza/sunsynk.git
> cd sunsynk/hass-addon-sunsynk
> docker build -t sunsynk
> cd ..   # change to the path containing config.json
> docker run -v $(pwd)/config.json:/config.json --name sunsynk sunsynk
> ```

These steps do not seem to work anymore. @kellerza what is your current preferred workflow for testing locally?
