### ISSUE TITLE
StandAlone Usage

### ISSUE THREAD

**Issue by box-daxter** [kellerza/sunsynk#32]
Hi!

I'm not using HA, I'm interested to run a Modbus -> mqttt bridge, runing on my RPI, besides my inversor. 
But I'm not running HA. There is some easy way, to modify the project or some scripts to work like that?

I have no experience with HA add-ons, so when I opened the code it was a mess for me.

Thanks.

**Comment by kellerza** [comment]
What environment do you have? Docker, or just Linux?

**Comment by kellerza** [comment]
Lets combine this with #31 a ask for a generic Docker container
