### ISSUE TITLE
Fault during the configuration

### ISSUE THREAD

**Issue by spanier106** [kellerza/sunsynk#329]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

Hello, I added and configured the addon according to these instructions 
 https://www.youtube.com/watch?v=X_ypBi7iuJc

Unfortunately I get the following error when saving:

Error saving the add-on configuration, expected int. Got {'DRIVER': 'solarman', 'INVERTERS': [{'SERIAL_NR': '203xxxxxxxxxxx34', 'HA_PREFIX': 'SS', 'MODBUS_ID': 1, 'DONGLE_SERIAL_NUMBER': 'E4Axxxxxxxx5', 'PORT': 'http://1xx.1xx.1xx.xx"'}], 'SENSOR_DEFINITIONS': 'single-phase', 'SENSORS': ['energy_management', 'power_flow_card ', 'pv2_power'], 'SENSORS_FIRST_INVERTER': ['settings'], 'MANUFACTURER': 'Sunsynk', 'READ_ALLOW_GAP': 2, 'READ_SENSORS_BATCH_SIZE': 20, 'SCHEDULES': [{'KEY': 'W' , 'READ_EVERY': 15, 'REPORT_EVERY': 60, 'CHANGE_ANY': False, 'CHANG...

**Expected behavior**

### Your environment

- Home Assistant version: 2024.8.2
- Addon:
  - Name: sunsynk-multi
  - Version: 2023-08-17
- Inverter:
  - Make: sunket inverter with E Linter WIFI Dongle
  - Model: \_\_
  - Firmware: \_\_
- Adaptor details:
  - RS485/RS232/solarman
  - RS485/RS232 brand

### You configuration

```yaml

paste config in the block surrounded by 3x backticks

```

### Logs

```logs

paste logs in 3x backticks...

```

**Comment by kellerza** [comment]
`DONGLE_SERIAL_NUMBER` should be an integer - the Pysolarman driver does not accept alphanumeric serial numbers

You probably have the wrong solarman dongle not compatible with https://pysolarmanv5.readthedocs.io/en/stable/
