### ISSUE TITLE
Unknown sensors 

### ISSUE THREAD

**Issue by Mk2AGU** [kellerza/sunsynk#330]
Existing sensor definitions can be found [here](https://github.com/kellerza/sunsynk/blob/main/src/sunsynk/definitions.py)

### You Inverter
Deye 8Kw 3phase inverter SUN-8K-SG04LP3-EU
Wiring rs485 Modebus port 

[Sunsynk/Deye Inverter Add-on (multi) V : 0.6.5 

Home Assistant

Core
2024.8.3
Supervisor
2024.08.0
Operating System
13.1
### Describe the issue/bug and what you expect

Hello I have many unknown sensors:
load voltage
 inverter current
 and various other's 

I tried a lot Load_L1_ current,load l1 current but I always get unknown sensor

So I inserted the sensors,

  - load_limit
  - Grid Charge enabled
  - Battery Max Charge current
  - Battery Max Discharge current
  - System Zero Export power
  - Overall state
  - Grid Charge Start Battery SOC
  - Grid Charge Battery current
  - Battery Shutdown Capacity
  - Battery Restart Capacity
  - priority_load

Any suggestions on proposed registers is welcome.

### Logs (if applicable)

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun sunsynk (no readiness notification)
s6-rc: info: service legacy-services successfully started
19:57:06 INFO    Loading configuration: /data/options.json
19:57:06 INFO    sunsynk library version: 0.6.4
19:57:06 INFO    Schedules:
+-----------+-----+------+--------+-----------+----------+------------+
|    Key    | src | Read | Report | Change by | Change % | Change any |
+-----------+-----+------+--------+-----------+----------+------------+
| date_time |     |  60  |   60   |           |          |    True    |
|     rw    |     |  5   |  300   |           |          |    True    |
|     w     |  *  |  1   |   2    |           |          |            |
|    kwh    |  *  |  15  |  300   |           |          |            |
|  any_unit |  *  |  1   |   2    |           |          |            |
|  no_unit  |     |  15  |  300   |           |          |    True    |
+-----------+-----+------+--------+-----------+----------+------------+
19:57:06 INFO    Using three phase sensor definitions.
19:57:06 ERROR   Unknown sensor specified: aux_power
19:57:06 ERROR   Unknown sensor specified: essential_power
19:57:06 ERROR   Unknown sensor specified: inverter_current
19:57:06 ERROR   Unknown sensor specified: load_frequency
19:57:06 ERROR   Unknown sensor specified: non_essential_power
19:57:06 ERROR   Unknown sensor specified: grid_charge_start_battery_soc
19:57:06 INFO    Added hidden sensors as other sensors depend on it: Rated power, Serial
19:57:06 INFO    Connecting to tcp://————-////
19:57:06 INFO    PyModbus 3.5.2 tcp: ——————-
19:57:06 INFO    Reading startup sensors Prog3 Time, Prog4 Time, Prog5 Time, Prog6 Time, Rated power, Prog2 Time, Serial, Battery Low Capacity, Prog1 Time
19:57:06 INFO    ############################################################
19:57:06 INFO                 Inverter serial number '****7812'
19:57:06 INFO    ############################################################
19:57:06 INFO    MQTT: Connecting to mqtt-user@core-mosquitto:1883
19:57:06 INFO    MQTT: Connection successful
19:57:07 INFO    Read every (inverter 1)
+----+----------------------------------------------------------------------------------+
| s  |                                     Sensors                                      |
+----+----------------------------------------------------------------------------------+
| 1  | grid_frequency, radiator_temperature, inverter_voltage, pv2_voltage, load_power, |
|    |     inverter_l3_power, inverter_frequency, battery_voltage, inverter_power,      |
|    |    pv2_current, inverter_l2_power, pv1_voltage, grid_l1_power, grid_l3_power,    |
|    |    gen_l1_power, gen_l2_power, grid_power, gen_l3_power, battery_temperature,    |
|    |    pv2_power, grid_current, gen_power, dc_transformer_temperature, pv1_power,    |
|    |      grid_ct_power, battery_soc, load_l1_power, load_l3_power, pv1_current,      |
|    | inverter_l1_power, battery_current, grid_voltage, battery_power, load_l2_power,  |
|    |                                  grid_l2_power                                   |
| 5  |       use_timer, prog1_power, prog5_charge, prog6_capacity, prog6_charge,        |
|    |  prog4_capacity, prog3_capacity, battery_restart_capacity, grid_charge_enabled,  |
|    |        prog1_capacity, load_limit, prog3_time, prog3_charge, prog5_power,        |
|    |     priority_load, grid_charge_battery_current, prog2_power, prog2_capacity,     |
|    |  battery_shutdown_capacity, system_zero_export_power, prog5_time, prog1_charge,  |
|    |  prog4_charge, prog6_power, prog6_time, prog2_time, battery_max_charge_current,  |
|    |       prog2_charge, prog3_power, prog5_capacity, prog4_time, prog4_power,        |
|    |         battery_max_discharge_current, battery_low_capacity, prog1_time          |
| 15 | total_pv_energy, total_battery_discharge, day_load_energy, total_battery_charge, |
|    |   day_battery_discharge, total_load_energy, day_battery_charge, day_pv_energy,   |
|    |      grid_connected, total_grid_import, day_gen_energy, day_active_energy,       |
|    |     day_grid_export, total_active_energy, total_grid_export, overall_state,      |
|    |                                 day_grid_import                                  |
+----+----------------------------------------------------------------------------------+
19:57:07 INFO    Report every (inverter 1)
+-----+----------------------------------------------------------------------------------+
|  s  |                                     Sensors                                      |
+-----+----------------------------------------------------------------------------------+
|  2  | grid_frequency, radiator_temperature, inverter_voltage, pv2_voltage, load_power, |
|     |     inverter_l3_power, inverter_frequency, battery_voltage, inverter_power,      |
|     |    pv2_current, inverter_l2_power, pv1_voltage, grid_l1_power, grid_l3_power,    |
|     |    gen_l1_power, gen_l2_power, grid_power, gen_l3_power, battery_temperature,    |
|     |    pv2_power, grid_current, gen_power, dc_transformer_temperature, pv1_power,    |
|     |      grid_ct_power, battery_soc, load_l1_power, load_l3_power, pv1_current,      |
|     | inverter_l1_power, battery_current, grid_voltage, battery_power, load_l2_power,  |
|     |                                  grid_l2_power                                   |
| 300 |      day_load_energy, use_timer, prog1_power, prog5_charge, prog6_capacity,      |
|     |         prog6_charge, prog4_capacity, total_grid_import, prog3_capacity,         |
|     | battery_restart_capacity, grid_charge_enabled, day_grid_export, prog1_capacity,  |
|     |     total_battery_charge, load_limit, prog3_time, prog3_charge, prog5_power,     |
|     |     priority_load, day_gen_energy, grid_charge_battery_current, prog2_power,     |
|     |       total_battery_discharge, prog2_capacity, battery_shutdown_capacity,        |
|     | day_battery_discharge, system_zero_export_power, prog5_time, day_battery_charge, |
|     | day_pv_energy, prog1_charge, prog4_charge, prog6_power, prog6_time, prog2_time,  |
|     |   battery_max_charge_current, prog2_charge, total_active_energy, prog3_power,    |
|     |    total_pv_energy, prog5_capacity, prog4_time, prog4_power, grid_connected,     |
|     |     battery_max_discharge_current, day_active_energy, battery_low_capacity,      |
|     | total_load_energy, prog1_time, total_grid_export, overall_state, day_grid_import |
+-----+----------------------------------------------------------------------------------+
20:03:34 INFO    Queue update battery_low_capacity=8
20:03:34 INFO    Writing sensor battery_low_capacity=8 Registers:{117=0x0008} 
20:04:05 INFO    Queue update battery_restart_capacity=20
20:04:06 INFO    Writing sensor battery_restart_capacity=20 Registers:{116=0x0014} 
13:53:03 INFO    Queue update prog1_capacity=8
13:53:04 INFO    Writing sensor prog1_capacity=8 Registers:{166=0x0008} 
13:53:24 INFO    Queue update prog1_capacity=10
13:53:24 INFO    Writing sensor prog1_capacity=10 Registers:{166=0x000a} 
13:53:52 INFO    Queue update grid_charge_enabled=ON
13:53:52 INFO    Writing sensor grid_charge_enabled=ON Registers:{130=0x0001} 
13:54:01 INFO    Queue update grid_charge_enabled=OFF
13:54:01 INFO    Writing sensor grid_charge_enabled=OFF Registers:{130=0x0000} 

paste logs in 3x backticks...

```

**Comment by kellerza** [comment]
The sensor names simply do not exist in the three phase definitions. Just remove them
