### ISSUE TITLE
Feature Request: Add 'Work Mode' as an option to allow "Selling First" and "Limited to Home"

### ISSUE THREAD

**Issue by gurmukhp** [kellerza/sunsynk#342]
Existing sensor definitions can be found [here](https://github.com/kellerza/sunsynk/blob/main/src/sunsynk/definitions.py)

### You Inverter

Details about your Inverter: SunSynk 3.6kW Ecco Hybrid Inverter

### Describe the issue/bug and what you expect

It would be great if we could change the 'Work Mode' in Home Assistant via MQTT so options like 'Selling First' and 'Limited to Home' can be set.

**Comment by kellerza** [comment]
Load limit = Allow export is probably what you want

**Comment by gurmukhp** [comment]
In the Sunsynk UI, I have the following for Work Mode.

- Selling First
- Zero Export + Limit to Load Only
- Limited to home

In the plugin, I have the following options for Load Limit:
- Allow Export
- Essentials
- Zero Export

Am I right in thinking that I probably need to change from 'Zero Export' to 'Allow Export' and then reverse?

**Comment by gurmukhp** [comment]
It works, thank you!

**Comment by kellerza** [comment]
👍  is it controlling the same register?

(Different naming for the same thing?)
