### ISSUE TITLE
ESP32 requires reset if Wifi intermittent

### ISSUE THREAD

**Issue by kcin-devil** [kellerza/sunsynk#345]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

Is there a way to verify the Wifi is connected, and if not either reset the ESP32 or re-initiate the setup loop? I had the ESP32 connected via the 12V outputs on the Inverter, but if for instance it looses connection to the WiFi for whatever reason, I need to reset the ESP32 for it to connect back to WiFi. As a work around I have the ESP32 powered via USB, plugged into a smart plug, if SOC becomes in a state unknown, I power cycle the smart plug, but I would prefer for it to only be connected via the Inverter power supply.

**Expected behavior**
Reset Wifi if disconnected

### Your environment

- Home Assistant version: 2024.9.2
- Addon:
  - Name: sunsynk-multi
  - Version: 2023-08-17
- Inverter:
  - Make: Sunsynk
  - Model: 8kW
  - Firmware: \_\_
- Adaptor details:
  - RS485/RS232/solarman
  - RS485/RS232 brand

### You configuration

```yaml

paste config in the block surrounded by 3x backticks

```

### Logs

```logs

paste logs in 3x backticks...

```

**Comment by kellerza** [comment]
Try the cabled solution :wink:

Can you post your addon config?
