### ISSUE TITLE
0.7.5 Update error

### ISSUE THREAD

**Issue by OwlBawl** [kellerza/sunsynk#352]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

get error notification in HA when trying update add-on from 0.7.4 to 0.7.5 via GUI

Can't install ghcr.io/kellerza/hass-addon-sunsynk-multi/amd64:0.7.5: 500 Server Error for http+docker://localhost/v1.45/images/create?tag=0.7.5&fromImage=ghcr.io%2Fkellerza%2Fhass-addon-sunsynk-multi%2Famd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

**Comment by ErnestoBrandao** [comment]
Same problem for me. and no 0.7.5 version for download

**Comment by czgif** [comment]
Hello,

I have same problem : get error notification in HA when trying update add-on from 0.7.4 to 0.7.5 via GUI

**Comment by eliesoldini** [comment]
Same here

**Comment by drevil54** [comment]
Hello,
I have same error:
Can't install ghcr.io/kellerza/hass-addon-sunsynk-multi/amd64:0.7.5: 500 Server Error for http+docker://localhost/v1.45/images/create?tag=0.7.5&fromImage=ghcr.io%2Fkellerza%2Fhass-addon-sunsynk-multi%2Famd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

**Comment by kellerza** [comment]
Please try again

**Comment by deondti** [comment]
I believe kellerza has fixed the issue, mine is working now

**Comment by drevil54** [comment]
yes, now update is working, thank you!
