### ISSUE TITLE
Scale size missing on month energy sensors

### ISSUE THREAD

**Issue by N1c084** [kellerza/sunsynk#45]
hi

Need to add the scalesize for these sensors

add KWH, 0.1), for each sensor

    Sensor(67, "Month Grid Energy", KWH, 0.1),
    Sensor(66, "Month Load Energy", KWH, 0.1),
    Sensor(65, "Month PV Energy", KWH, 0.1),

**Comment by N1c084** [comment]
i do a PR from my fork, but i do not know if i do it well?
I do not see anything here, only on my fork, please confirm if you receving a PR?

**Comment by kellerza** [comment]
#46 thanks!
