### ISSUE TITLE
rw sensor not change state in real

### ISSUE THREAD

**Issue by N1c084** [kellerza/sunsynk#50]
Hi 
in last revision
I changed the low  batt value , we can see the write state chaging but the read state stay the same, so inverter do not take the value.

![image](https://user-images.githubusercontent.com/101097267/181903000-42c4a56b-67e6-4f4f-819f-f40137926a03.png)

Is it possible to Read/write value from nodeRed to RW sensors?

thanks

**Comment by Ivan-L** [comment]
Hi @N1c084, just to understand, did you change the "Battery Low Capacity" register on the inverter itself and you do not see the effect in the add-on?
Currently the "Battery Low Capacity" sensor is not a R/W sensor in this add-on, so I am just trying to understand how you were able to change it if not on the inverter?

**Comment by N1c084** [comment]
Hi @Ivan-L 
I added the sensor to set it to HA, but I confused the "prog 2 capacity" and "low battery capacity" sensors which is not R/W, sorry for the confusion.
