### ISSUE TITLE
Initial reading issues

### ISSUE THREAD

**Issue by e1ace** [kellerza/sunsynk#66]
This is more a Home Assistant issue (or rather my understanding of how this is supposed to work). 

I have successfully connected to the inverter and can get the required sensors, but the energy dashboard shows the initial reading as the total reading stored by the inverter. Is this intended? Will I just need to live with this data point being at a very high scale. I'm aware that over the next few hours it will just show the increasing value, but it would be great to not have this large 'spike'.

![Screenshot 2022-10-26 171136](https://user-images.githubusercontent.com/20770537/198064985-afbdda02-f238-4321-b78e-d2a4f5bafdfe.png)

**Comment by kellerza** [comment]
Glad you got it working!

If this spike is (still) a big issue, you could always edit the underlying database. I'm sure there would be some suggestions on the HA Community forum.
