### ISSUE TITLE
Connect to Port by ID instead of Device Path

### ISSUE THREAD

**Issue by e1ace** [kellerza/sunsynk#67]
Right now it seems like the Port settings has to be in the Device Path format "/dev/ttyUSB0". 

Is it possible to support the device ID instead "/dev/serial/by-id/usb-FTDI_USB-RS485_Cable_FTZ29WM6-if00-port0"?

The device path seems to change frequently when you have multiple devices in Home Assistant OS.

**Comment by kellerza** [comment]
If you insert a “port” string it ignores the selected device

![Uploading 082EABB5-0A82-4845-9012-4540ACD344CD.jpeg…]()

**Comment by kellerza** [comment]
![D987E272-076F-426F-B19A-E92E92A39716](https://user-images.githubusercontent.com/6756881/199534688-2b9acbd5-f8ff-49f7-8884-45d09604a70b.jpeg)

Try serial:///dev/abcded in the port field

**Comment by e1ace** [comment]
Thanks. I've moved to the dev branch and I can now see the settings above.
