### ISSUE TITLE
Wiring Diagram RS485 RJ45

### ISSUE THREAD

**Issue by tuanha2000vn** [kellerza/sunsynk#7]
![image](https://user-images.githubusercontent.com/2765517/151664488-5b63b642-ea0e-4eb3-b878-3d6d404d746b.png)
![image](https://user-images.githubusercontent.com/2765517/151664508-0013315f-a38a-4b45-84f7-1ce367c4e0eb.png)
Hi, I'm trying to connect Home Assistant to Deye inverter using USB-RS485-RJ45 cable.

What the correct way to wire the cable?

Option 1:  USB-RS485 A/D+ to RJ45 1 - USB-RS485 B/D1 to RJ45 8
Option 2:  USB-RS485 A/D+ to RJ45 8 - USB-RS485 B/D1 to RJ45 1

Thank you.

**Comment by tuanha2000vn** [comment]
![image](https://user-images.githubusercontent.com/2765517/151664726-e3dcb529-64cb-4d67-9140-7d74d06be68c.png)

Found this on the user manual, that mean this?
RJ45 1 and 8 to RS485 A/D+
RJ45 2 and 7 to RS485 B/D-

**Comment by kellerza** [comment]
I documented my wiring [here](https://github.com/kellerza/sunsynk#hardware)

Below is a 568A plug...

<img width="193" alt="image" src="https://user-images.githubusercontent.com/6756881/151664788-2cf17cba-28ee-4d1b-b72f-41669ccbf07c.png">

**Comment by kellerza** [comment]
The Readme now has some more info...
