### ISSUE TITLE
Any idea what the unlisted inverter faults mean

### ISSUE THREAD

**Issue by cods4** [kellerza/sunsynk#71]
My inverters are always showing some sort of fault on the fault sensor, but none of them are listed on the manual or anywhere else I can find.

Surely they have some meaning, does anyone know what they are?
The ones I have are F65 through to F73

**Comment by louispires** [comment]
Also wondered the same thing.

Mine always shows these 3: 
![image](https://user-images.githubusercontent.com/8841644/204790411-ff9e3214-91ca-4c13-be00-5a77b37b12f0.png)

I have in the past seen an error on my Inverter, BMS Failure but the HA integration never changed...

**Comment by kellerza** [comment]
No idea to be honest, I really don't use this sensor, my sensor shows: F66, F67, F68, F70, F71. 
Everything seems ok on the inverter though.

I've never tried to test the [FaultSensor](https://github.com/kellerza/sunsynk/blob/main/sunsynk/sensor.py#L386) so no idea if it even works, it's simply my interpretation of the Sunsynk Modbus document. Open for PRs/suggestions

**Comment by kellerza** [comment]
It seems this was solved by removing register 107 from the sensor.

Changes might only be in the multi version

**Comment by kellerza** [comment]
Please check and let me know if still an issue?

**Comment by cods4** [comment]
Yeh I noticed they were gone, which I guess solves it.

Thanks Johann
