### ISSUE TITLE
DEVICE isn't documented

### ISSUE THREAD

**Issue by reedy** [kellerza/sunsynk#73]
https://github.com/kellerza/sunsynk/blob/main/hass-addon-sunsynk/DOCS.md doesn't describe at all what `DEVICE` is (other than mentioning it in the bullet point), while giving docs that show the YAML.

**Comment by kellerza** [comment]
DEVICE is a selectable USB device in the HomeAssistant UI.

PORT should be an empty string when you want to use the selected device, otherwise PORT is preferred

**Comment by reedy** [comment]
But DEVICE seemingly can't be empty (which is more likely to happen if just setting via yaml), when it should be able to be when you're using one of the "proxies" or basically the RS485 adapter plugged into the device

**Comment by kellerza** [comment]
Just select any DEVICE, PORT is preferred if present.

**Comment by reedy** [comment]
Yeah, I know.

But it should be at least documented to say this..
