### ISSUE TITLE
Sunsynk inverter data over HTTP rest/api

### ISSUE THREAD

**Issue by renegadeandy** [kellerza/sunsynk#79]
Hi all.

Sorry for opening an issue as this is more of a question.

We have a sunsynk inverter, connected through the official dongle to our wireless network, and access data regarding our solar setup via the official sunsynk connect app.

I want to access the data from the inverter directly rather than via the app, ideally over a rest / api.

I have done research but can't figure out what the interface is or if there is an api endpoint I can just fire requests at via the inverter - as it is on the network this feels like it has to be possible.

Any ideas, examples of this?

**Comment by kellerza** [comment]
There are people that directly get data from the Solarman dongle - you should try searching powerforum.co.za. I never tried it, but it requires you to get an API key from them and the data will still be significantly delayed.

The `sunsynk` Python library in this repo will allow you to read the data (via RS485/RS232) and then you can serve it in your own app through a REST endpoint.

The addons in this repo are used in Home Assistant OS and reads data periodically and then publishes it to Home Assistant via MQTT. You can get access to this data either via MQTT, or by querying the HASS REST endpoint for the state of the various sensors. In this case you would need Home Assistant, but the hardware requirements would be a Raspberry Pi + an RS485 dongle that can run HASS+the addon
