### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by timclark0000** [kellerza/sunsynk#86]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

Following error message when attempting to install add-on:

"The command '/bin/ash -o pipefail -c pip3 install --no-cache-dir --disable-pip-version-check paho-mqtt~=1.5.0 pyyaml~=5.4.1 sunsynk[pymodbus,umodbus]==0.2.5' returned a non-zero code: 1"

**Expected behavior**

### Your environment

- Home Assistant version: 2022.12.1
- Addon version:2022.11.29-0.2.5
- Inverter make: Sunsynk
- Inverter Model: \_\_
- Inverter Firmware: \_\_

### Logs

```log
paste logs in 3x backticks...
```

**Comment by kellerza** [comment]
You can try installing the dev version of the addon, but my first thought would be that you have bad DNS/Internet connectivity

Can you configure static IP&DNS on your HASS/raspberry pi?

**Comment by timclark0000** [comment]
Thanks for your response. I've tried the dev version but it throws the same error. I've reconfigured my network with five different DNS servers now and each one also produces the same error. My Home Assistant instance is running in VirtualBox on a Windows 10 machine, if that helps at all. Happy to try changing various parameters at home to test this.

**Comment by kellerza** [comment]
Any feedback?

**Comment by amctear** [comment]
Hi All,
Not sure how to address my HF2221 Modbus server to Ethernet, - Port, Device & Driver ?  Any suggestions ?

![Screenshot 2023-01-27 230349](https://user-images.githubusercontent.com/7934654/215222440-eec81fcb-f164-46f4-8423-93bd8337f9c3.jpg)

)

**Comment by kellerza** [comment]
The driver is ok, and device is ignored when you have a port

**Comment by amctear** [comment]
> The driver is ok, and device is ignored when you have a port

Perhaps the wiring to the inverter id my problem.  I understand you tried a HF5142B, what was your wiring ?   
I've currently 

Green/White to T-
Green to T+
Orange/White to GND

Thoughts please 

![HF2221](https://user-images.githubusercontent.com/7934654/215279292-9abd8c3d-f024-48fb-b655-d21729a353e5.jpg)

**Comment by amctear** [comment]
Got it working and so very happy and 3 or 4 days pulling my hair out. Feeling rather proud of myself now :-)

My mistake was the wiring of the CAT 5 cable to the Modbus Server,  it wasn't 
Green/White to T-
Green to T+
Orange/White to GND

Ended up being Wires 2 & 7 to A  and  1 & 8 to B.  Modbus Poll imediately :-) 👍

**Comment by kellerza** [comment]
Ideally you should not have to wire both 1&2 AND 7&8, but if this is working for you its probably ok. The are other people on powerforum also doing this

**Comment by kellerza** [comment]
Closing as there is no response from @timclark0000 and his problem is related to the environment rather than the addon
