### ISSUE TITLE
Sensorts auto-complete

### ISSUE THREAD

**Issue by jackkitley** [kellerza/sunsynk#89]
### Describe the issue/bug

For the sensors section in config i would imagine this to be autocomplete? I cant seem to get any values to display here. Even if i remove an existing sensor and try to add it back again i cant find it.

### Expected behavior

I expect all available sensors to be displayed for selection.

### Logs (if applicable)

```log
paste logs in 3x backticks...
```

**Comment by kellerza** [comment]
Sorry, there are no plans to do this. Unfortunately you'll have to read the docs.

But since it's open source you are welcome to add it yourself
