### ISSUE TITLE
AC on/off status

### ISSUE THREAD

**Issue by dirkackerman** [kellerza/sunsynk#9]
Hi @kellerza,

Do you maybe know if any of the sensors in definitions.py will map to an AC on/off state, simular to the LED on the front pannel?

Also, is the implementation in definitions.py complete and if not, do you have documentation you can share on the API or are you reverse engineering the protocol?

Thanks,

Dirk

**Comment by kellerza** [comment]
You can use either grid voltage or frequency and create a template binary_sensor 
Value template `{{ sensor.grid_frequency > 0 }}`. I used a document named: sunsynk modbus (no chinese) that I got powerforum, do not have the exact link, feel free to email me if you cannot find it

**Comment by kellerza** [comment]
There are some interesting new ones I'm looking at to write settings. It will be via a MQTT select entity and be based on profiles, rather than individual selects

```python
prog1_time = Sensor(250, "Prog1 Time", func=timef)
prog2_time = Sensor(251, "Prog2 Time", func=timef)
prog3_time = Sensor(252, "Prog3 Time", func=timef)
prog4_time = Sensor(253, "Prog4 Time", func=timef)
prog5_time = Sensor(254, "Prog5 Time", func=timef)
prog6_time = Sensor(255, "Prog6 Time", func=timef)

prog1_power = Sensor(256, "Prog1 Power", "W", 1)
prog2_power = Sensor(257, "Prog2 Power", "W", 1)
prog3_power = Sensor(258, "Prog3 Power", "W", 1)
prog4_power = Sensor(259, "Prog4 Power", "W", 1)
prog5_power = Sensor(260, "Prog5 Power", "W", 1)
prog6_power = Sensor(261, "Prog6 Power", "W", 1)

prog1_capacity = Sensor(268, "Prog1 Capacity", "%", 1)
prog2_capacity = Sensor(269, "Prog2 Capacity", "%", 1)
prog3_capacity = Sensor(270, "Prog3 Capacity", "%", 1)
prog4_capacity = Sensor(271, "Prog4 Capacity", "%", 1)
prog5_capacity = Sensor(272, "Prog5 Capacity", "%", 1)
prog6_capacity = Sensor(273, "Prog6 Capacity", "%", 1)

# 1- Grid, 2- Gen, 4- ?
prog1_charge = Sensor(274, "Prog1 Charge")
prog2_charge = Sensor(275, "Prog2 Charge")
prog3_charge = Sensor(276, "Prog3 Charge")
prog4_charge = Sensor(277, "Prog4 Charge")
prog5_charge = Sensor(278, "Prog5 Charge")
prog6_charge = Sensor(279, "Prog6 Charge")
```
